### ISSUE TITLE
PIPL03- Similarity search error

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#1]
** machine- PIPL03
version- v2_test**
Log window shows similarity search is completed, but no results.

![similarity search error](https://user-images.githubusercontent.com/111036161/184088502-fa7f3d92-ea72-42e4-9cfe-bc15e7ec3267.JPG)
![similarity terminal](https://user-images.githubusercontent.com/111036161/184088505-efd28052-5c3c-4c2e-b37d-b8504b837726.JPG)

**Comment by SumedhaBhosale** [comment]
Sometime, If query compound doesn't found any similar compounds, it gives blank string in API which results in blank page of software. 
We can put up a message here saying "No similar compounds found"

**Comment by mdaakhan** [comment]
@LobeliaG Please provide the input which you have given, it is requested please provide the input of the time of the bug report and the exact location in the software.

**Comment by LobeliaG** [comment]
Yes sir. Just provided.

**Comment by bishweshwarShome** [comment]
uniprot P29474 

error not reproduced.

**Comment by mdaakhan** [comment]
Fixed 
V1: Commit ID: 9c8d352
V2: Commit ID: c1d85b8
