### ISSUE TITLE
BindingDB : Similar Drugs

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/ChemIn#10]
Hi,

Similar Drug search using BindingDB ID in ChEMBL is giving blank tab. 

![ChemIn_SimilarDrugs_ChEMBLOutput](https://user-images.githubusercontent.com/105902516/190326171-95e85bc2-be0b-4638-abb5-f1cdbd95407e.jpg)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  80f062b
