### ISSUE TITLE
Shortcut of opening already existing project

### ISSUE THREAD

**Issue by gurdev7** [chandkc/ChemIn#13]
If I click on chemIn icon and want to open existing project directory instead of opening this pop up a different pop up should be better i. e. "You are opening an existing project directory. Continue or not?"

<img width="684" alt="Screenshot 2022-09-16 at 10 46 09 AM" src="https://user-images.githubusercontent.com/113581903/190562046-e2273e89-b7ed-4481-89d0-034d06bd98a0.png">

**Comment by bishweshwarShome** [comment]
To open an existing project you have to click on File then Open Recent Projects.

This pop-up is coming because there are settings folder and data.prescience file in that existing project directory.
