### ISSUE TITLE
Suggestion : What to do when API is not responding ?

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/ChemIn#15]
hi.

At times when APIs from databases are not responding, on sw UI part we cannot realise this. User will only see that sw is not getting ahead and probably something is wrong with sw which is not the correct case. Hence I have a suggestion to put a pop-up/log message saying "API not responding". 
@bishweshwarShome - Please take a look if we can do this.

**Comment by bishweshwarShome** [comment]
added.

commit id:  80f062b
