### ISSUE TITLE
Similar drug search not working

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#16]
PIPL01
windows- TEST_V2_10

1.Similar drug search is non- functional. After selecting ok in the pop up, nothing happens.
![image](https://user-images.githubusercontent.com/111036161/192512381-d6b2f45d-d8b1-4aee-87b7-8929e4bfc7f6.png)
2. Select/unselect all buttons non functional in drug properties page.

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  80f062b
