### ISSUE TITLE
CHEMIN similar drug search option not working

### ISSUE THREAD

**Issue by parulok** [chandkc/ChemIn#17]
when we select molecule from uniprot search, it is not further connecting to similar drug search in CHMEBL
selected percentage 10 and 50 but both not working

![bug4](https://user-images.githubusercontent.com/113584310/192699099-a25e4859-cd29-4087-bc6e-e56ccec22d25.png)

**Comment by bishweshwarShome** [comment]
fixed.
commit id:  80f062b
