### ISSUE TITLE
CHEMIN- similar drug search option not working

### ISSUE THREAD

**Issue by parulok** [chandkc/ChemIn#18]
when we select molecule from uniprot search, it is not further connecting to similar drug search in CHEMBL and BINDINF DB
selected percentage 10 and 50 but both not working 
also tried by selecting only CHEMBL still no success
![bug4](https://user-images.githubusercontent.com/113584310/192697100-15206231-a124-4a75-9610-80393bb4acac.png)

**Comment by bishweshwarShome** [comment]
fixed.
commit id:  80f062b
