### ISSUE TITLE
Show activity

### ISSUE THREAD

**Issue by gurdev7** [chandkc/ChemIn#26]
Clicking show activity does not return anything.

<img width="1338" alt="Screenshot 2022-10-18 at 10 14 39 AM" src="https://user-images.githubusercontent.com/113581903/196337589-873bb378-3010-4c02-831b-0c9428eb617d.png">

return this

<img width="1338" alt="Screenshot 2022-10-18 at 10 16 02 AM" src="https://user-images.githubusercontent.com/113581903/196337673-f5d3c818-67c0-462e-868b-a2bb32a0fb0c.png">

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  88c46c5
