### ISSUE TITLE
Error while  searching similar drug search

### ISSUE THREAD

**Issue by gurdev7** [chandkc/ChemIn#28]
I am selecting compound but it is still throwing error.
1. Similar drug search.
2. BindingDB database throw error.
3. Only selecting ChemBL now.
4. That error.

![Uploading Screenshot 2022-10-18 at 10.28.32 AM.png…]()

**Comment by bishweshwarShome** [comment]
image not visible.

that time there was problem in BindingDB API . not it's working.
