### ISSUE TITLE
Binding DB -Not fetching information Returns error

### ISSUE THREAD

**Issue by lingeshram777** [chandkc/ChemIn#29]
1.Uniprot ID Q07343, Chembl: Returns 2674 Molecules
Similar Drug search (Chembl & BD Search Separately) 
Searching in Chembl: Returns 582.
Searching in BD: 40% & 80% Similarity, ***Error:*no similar drugs found and Service Unavailable, Server error, please try again later.****

![ChemIn_BD2](https://user-images.githubusercontent.com/113585176/196863505-236adf3f-2ac7-41ba-b70b-fbc1523c0f43.png)
![ChemIn_BD1](https://user-images.githubusercontent.com/113585176/196863510-80aa5169-8de4-4b2e-bc50-5d5437fe4a29.png)

2.Uniprot ID Q07343, Searching in Binding DB .
Binding DB: Returns 2921 Molecules.
When Click Show activity:  **Error: Binding DB server error, please try again later. (Tried Multiple attempts with various time interval).**

**Comment by bishweshwarShome** [comment]
BindingDB server issue.
