### ISSUE TITLE
chemIn - No ChemBLID results

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/ChemIn#3]
For results when there is no chembl ID for query protein/drug, user should get notification that he can't go ahead with this.

**Comment by mdaakhan** [comment]
@SumedhaBhosale Please specify the exact position in the software, also the input given so that we can check and fix it

**Comment by bishweshwarShome** [comment]
same issue, already fixed and committed.

v1:  9c8d352
v2:  c1d85b8

**Comment by SumedhaBhosale** [comment]
Hi,

Somehow its still not working. 

Linux OS 
Exe shared on 24 Aug
Uniprot ID : P06213.
Database used : uniprotkb 

Compound chosen - CHEMBL1800685  from "Compounds" tab. Then go for Similar Drug Search. 

Sharing screenshots for help 

![SimilarDrugSearch_Details](https://user-images.githubusercontent.com/105902516/186609146-2e87834c-4c0a-4256-91df-21f843aed4aa.png)

![SimilarSearch_ChemIn_Compounds](https://user-images.githubusercontent.com/105902516/186609189-a05f1d09-f8ca-4724-94b0-860115985b63.png)

![SimilarSearch_ChemIn](https://user-images.githubusercontent.com/105902516/186609222-6776e6df-2ba8-4deb-ac35-2cdf596a4eef.png)

**Comment by SumedhaBhosale** [comment]
For some compounds, results for similarity search can be seen. For some, there is blank page (see above screenshot3). Probably these compounds don't have any similar compounds in db. So we can throw message saying "No similar compounds found".

**Comment by mdaakhan** [comment]
This modification is fixed today and will be reflected in next release
