### ISSUE TITLE
Wrong information while no associated compounds for uniprot ID

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/ChemIn#30]
version- PRinS_Ubuntu_2_0_3_Test

For uniprot ID- P22304
that doesn't have associated compounds, the popup shows error as server not available.

![Screen Shot 2022-10-20 at 11 23 45 PM](https://user-images.githubusercontent.com/105898169/197112201-af6681a4-b148-4ccc-ac72-8e4c52ca6ea4.png)

**Comment by bishweshwarShome** [comment]
![Screenshot from 2022-10-21 11-26-04](https://user-images.githubusercontent.com/108135149/197123027-838b3b40-bf97-4248-92d9-4a13a0c61a23.png)

**Comment by bishweshwarShome** [comment]
Here, for this uniprot id: P22304 , BindingDB API response status code is 500.
That's why giving this info message. Should we give some other info message ?

@bishweshwarShome @prescienceit @aiswaryapawar

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  982cfba
