### ISSUE TITLE
similarity search in binidngDB error

### ISSUE THREAD

**Issue by aiswaryapawar** [chandkc/ChemIn#31]
version- PRinS_Ubuntu_2_0_3_Test

the Bindingdb search error while looking for similar drugs
![Screen Shot 2022-10-20 at 11 19 44 PM](https://user-images.githubusercontent.com/105898169/197112710-df002b3c-091f-487e-b207-a9566df37014.png)
![Screen Shot 2022-10-20 at 11 19 59 PM](https://user-images.githubusercontent.com/105898169/197112714-965a52b5-c847-42b1-b8aa-35e10cf3794e.png)
![Screen Shot 2022-10-20 at 11 20 09 PM](https://user-images.githubusercontent.com/105898169/197112721-f6af7847-5daf-4185-b956-3d8066dd8d7f.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  eebecaf
