### ISSUE TITLE
Search Similar Compound button not working

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#32]
Software - PRinS_Ubuntu_20_86X64_2_0_0
Smile search is not working, selected ChEMBL as database with drug as an entity.
![Screenshot from 2022-11-21 17-39-10](https://user-images.githubusercontent.com/117424735/203052163-fa890f0b-fcb5-4ee7-9e8f-47112449f86c.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  982cfba
