### ISSUE TITLE
Unable to select the compounds after blast and fasta search

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#33]
**PRinS_Ubuntu_20_86X64_2_0_0**
The checkbox for selection is not visible after performing blast and fasta. Also the blank space is becoming editable
Sequence used was GAHMEWKLFADLAEVAGSRTVRVDVDGDATVGDALDALVGAHPALESRVFGDDGELYDHINVLRNGEAAALGEATAAGDELALFPPVSGG
![Screenshot from 2022-11-21 15-33-12](https://user-images.githubusercontent.com/117424735/203053980-d48f3579-ae9c-4cb6-b0d8-508ded4c7429.png)

**Comment by bishweshwarShome** [comment]
for now, "NA" is not there (from the API), we can check it later.
