### ISSUE TITLE
No Drug Properties for Similar IDs

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#34]
**PRinS_Ubuntu_20_86X64_2_0_0
Linux**

The Drug Properties is only given for compounds under the column ChEMBL ID. It would be nice if the drug properties is also shown for compounds under Similar ID. 
For example, after selecting all 4 compounds from Similar Drugs I am getting Drug Properties only for compounds listed under ChEMBL ID. 

![ChemIn_3](https://user-images.githubusercontent.com/117424735/204218629-9b99b759-1c88-4ed4-a1b3-60f464b337d6.png)
![ChemIn_4](https://user-images.githubusercontent.com/117424735/204218620-75661ca4-8436-4d4e-a255-b3495774c1b6.png)

**Comment by bishweshwarShome** [comment]
It's working.  ( BindingDB similar drug search API issue )
