### ISSUE TITLE
SyMogAI 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#35]
**PRinS3_Installer_Ubuntu_20_04_x64**
**Linux**

SyMog/AI is opening even when nothing is selected. A pop up should come saying something like _**Please select minimum 1 compound**_.

[SyMoGAI.webm](https://user-images.githubusercontent.com/117424735/204266874-cf4dfc15-4761-4139-8d99-44b8a2e3cdae.webm)

**Comment by bishweshwarShome** [comment]
fixed.


commit id :  b57ecb2
