### ISSUE TITLE
Software closes when clicking on dark mode  

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#36]
**PRinS_Ubuntu_20_86X64_2_0_0**

The software is closing automatically when I click on dark mode of plots for similar drug or drug properties. This only happens for distribution plot and not for scatter plot.

[ChemIn.webm](https://user-images.githubusercontent.com/117424735/209643651-b4c6f756-8f81-4f01-8327-7f4701eeddf6.webm)

![ChemIn_terminal](https://user-images.githubusercontent.com/117424735/209643555-abb84dc7-bf39-403e-af04-6092a78b467f.png)

**Comment by bishweshwarShome** [comment]
Fixed.

Commit id: 2e71e40
