### ISSUE TITLE
NA in chembl id after blast and fasta search

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#37]
**PRinS_Ubuntu_20_86X64_2_0_0**
PDB ID - 5WY0 https://www.rcsb.org/structure/5WY0
Sequence - https://www.rcsb.org/fasta/entry/5WY0/display

At the time of blast or fasta search, many a times in output there is NA in chembl id column. 
For example, fasta sequence search for PDB ID 5WY0 is giving NAs for chembl id in every row. **No** chembl id found for this particular search. This can be confusing for user as the Associate Drug Search results will also be blank.

**Suggestion** - A pop up should come informing user that no chembl id is found associated to their search and they cannot proceed forward or a pop up suggesting what the user can do next. 

![ChemIn_FastaSearch](https://user-images.githubusercontent.com/117424735/210198755-41ffd026-fd35-401e-a9e8-df12bd16410f.png)

![ChemIn_parameters](https://user-images.githubusercontent.com/117424735/210198896-128120d7-4435-4386-9b55-2edf5c3c92a6.png)

**Comment by bishweshwarShome** [comment]
for now, "NA" is not there (from the API), we can check it later.
