### ISSUE TITLE
Unable to generate pdbs

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#38]
Windows - PRinS_Installer_WIN10_x64
version - latest v 2.0.0

PDBs are not getting generated but smi files are getting generated. For parameters, ChEMBL database was selected with uniprot id P03366

![chemin_1](https://user-images.githubusercontent.com/117424735/211778913-09989798-4a4f-44e3-b38e-78fbd60504b9.png)

![chemin_2](https://user-images.githubusercontent.com/117424735/211778922-dc77a228-b8a3-4ef4-8499-a517907b46b2.png)

**Comment by bishweshwarShome** [comment]
Cannot reproduce the issue,
