### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#39]
Windows - PRinS_Installer_WIN10_x64
version - latest v 2.0.0

All the checkbox are not getting selected when I click on _**select all**_. Did a fasta sequence search for protein with pdb id [3PIY](https://www.rcsb.org/fasta/entry/3PIY/display)

https://user-images.githubusercontent.com/117424735/211790637-214d4875-80e5-469a-b17b-f44cf52c3b12.mp4

**Comment by bishweshwarShome** [comment]
for now, "NA" is not there (from the API), we can check it later.
