### ISSUE TITLE
PIPL01-Error with BindingDB inputs

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#4]
**machine-PIPL01
software- TEST_V2_3- windows version**

Incase of **BindingDB** database inputs, after generating similar drugs when we select some of them and try to generate Drug properties the following pop up shows up- 
![image](https://user-images.githubusercontent.com/111036161/187144530-22935d33-c971-412f-ab2b-d6aee974bf84.png)
 So after the failure of the software to recognize manual selection, I went for 'select all' option from the tools section. However, it created selection boxes in the Tanimoto coefficient Tab. In this Tab deselection of any compound manually also could not be done. Drug property generation is only working for all selected compounds through 'select all' option at the moment. 'Select' boxes are totally non-functional. However, when using inputs from other database like ChemBL, things are working fine.
![image](https://user-images.githubusercontent.com/111036161/187145890-09de2f8c-d5c4-4432-bfd1-022c5df5cdb7.png)

After that drug property search is also not working properly for this.
![image](https://user-images.githubusercontent.com/111036161/187149197-4d4383f6-42c6-4f18-b803-f91779d6252a.png)

**Comment by LobeliaG** [comment]
Database chosen- BindingDB
tested UniProt IDs - Q9NR97, P40763

**Comment by bishweshwarShome** [comment]
show drug properties is not implemented yet for BindingDB, will work on it after discussion (flow).

**Comment by bishweshwarShome** [comment]
fixed and committed.

Commit ID: 042314e
