### ISSUE TITLE
Cancel button for PDBs 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#40]
Windows - PRinS_Installer_WIN10_x64
version - latest v 2.0.0

At the time of downloading pdbs, if I clicked on cancel then I am getting success pop up and files are getting saved in working project directory

![chemin_3](https://user-images.githubusercontent.com/117424735/211997075-9f1b7440-c813-4519-a436-7c7243e873fa.png)

**Comment by bishweshwarShome** [comment]
fixed
