### ISSUE TITLE
Sequence file is getting erased

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#41]
Windows - PRinS_Installer_WIN10_x64
version - latest v 2.0.0

When a sequence file is provided by browsing and then the same or a different file is provided again, the sequence in that particular file is erased.
Also, the input space (red rectangle) for browse file is editable, this can be made static.

![chemin_4](https://user-images.githubusercontent.com/117424735/212242188-95c1fae7-0777-4ff6-8434-df3cf60851d9.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  866a990
