### ISSUE TITLE
COCONUTDB issues!

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#42]
Version - Open bundle **V2_TEST**
OS - **Linux**

1. Checkbox are not properly visible
2. **_Compounds filter_** is not working
3. No Tanimoto column in **_similar_drug.csv_**
4. No Mol. Weight column in **_drug_properties.csv_**
5. While exporting .csv files, a success pop up appears when click on cancel button
6. If none of the compounds are selected then too symogai opens, a pop up should come saying please select at least 1 compound.
7. **_Show drug properties_** is showing drug properties of all the compounds irrespective of selection 
8. Different results for same set of smiles if given manually and given by text file
9. PDB files are not formed. _[pdb files could not be genereated please try again later and check you local docker environment error]_
10. Graphical representation for scatter plot is not proper (number of molecules on x-axis)

![Screenshot from 2023-01-20 10-39-17](https://user-images.githubusercontent.com/117424735/213621952-099a3308-7bb5-4c18-961c-9ee848e64a0c.png)
![Screenshot from 2023-01-20 10-37-08](https://user-images.githubusercontent.com/117424735/213621954-a83b3c02-9465-4edc-b48f-e67d2477f602.png)

**Comment by bishweshwarShome** [comment]
fixed.

commit id: 57d3d65
