### ISSUE TITLE
None - drug properties

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#43]
**Linux** - PRinS_Ubuntu_20_86X64_2_0_0
**Windows** - PRinS_Installer_WIN10_x64  (latest v 2.0.0)

**Uniprot id** - P27824

If drug properties for compounds are not found then **None** is displayed as output for linux and blank results for windows.

**LINUX**
![Screenshot from 2023-02-02 10-28-17](https://user-images.githubusercontent.com/117424735/216236007-07a74c70-fbc3-4874-bd7c-2a233de98462.png)

**WINDOWS**
![chemin_windows](https://user-images.githubusercontent.com/117424735/216236058-480a38d0-6b26-453b-bebd-f2538fad184f.png)

**Comment by bishweshwarShome** [comment]
fixed
