### ISSUE TITLE
COCONUTDB - V2 issues

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#44]
**Version - V2_TEST
OS - Linux/ Windows**

1. Software is getting crashed when smiles are given manually and in txt file. This happens when the number of smiles are more. Tested with 9 smiles (windows and linux)
2. compounds_result.csv is blank (windows)
3. csv file is not properly aligned (linux)
4. Checkbox is not properly visible in linux
5. Unable to download pdb files (linux and windows)

**Error message when software is crashed**
<img width="369" alt="Screenshot 2023-02-06 at 10 55 34 AM" src="https://user-images.githubusercontent.com/117424735/216890489-81bdec03-70a2-4f06-822f-4da002f0abdb.png">

**Comment by bishweshwarShome** [comment]
partially fixed.

**Comment by mdaakhan** [comment]
Already Solved in the previous version
