### ISSUE TITLE
COCONUTDB - V2 issues

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#45]
Version - V2_TEST
OS - Linux

1. **_Search Similar Compounds_** gets inactive if clicked on plus button.
2. The headers are changing when clicked on **_Molecular Weight_** column of fetched **_Compounds_**

[Screencast from 09-02-23 02:48:31 PM IST.webm](https://user-images.githubusercontent.com/117424735/217808922-a8e818cd-83ae-4030-9e9f-e5a1a6b52a42.webm)

[Screencast from 09-02-23 03:36:25 PM IST.webm](https://user-images.githubusercontent.com/117424735/217808823-9169fc89-fb38-4ddc-b7d2-9ca334483100.webm)

**Comment by bishweshwarShome** [comment]
fixed
