### ISSUE TITLE
Log and duplicates in associated drugs

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#47]
**Version** - V2_TEST
**OS** - Linux

Parameters given
Database - ChEMBL, Search using - Sequence for uniprot id **P02649**

1. The associated drug search results are showing duplicates when selected every uniprot id in previous step.
2. The log is not displaying proper message for sequence results. It is only displaying **Sequence extraction completed** but the information about uniprot id is missing
3. No space between ChEMBL id and smiles in logs while generating pdbs.

![Screenshot from 2023-02-17 10-21-11](https://user-images.githubusercontent.com/117424735/219553030-0865a5d2-1987-471d-b61b-98208f12e608.png)

![Screenshot from 2023-02-17 16-14-58](https://user-images.githubusercontent.com/117424735/219630676-1af8fdae-f8a1-4129-8629-5f39ae114e86.png)

![Screenshot from 2023-02-17 11-04-10](https://user-images.githubusercontent.com/117424735/219631559-08b50215-d032-4399-855c-b50eba6fe657.png)

**Comment by bishweshwarShome** [comment]
fixed
