### ISSUE TITLE
Multiple alerts!

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#48]
**Version** - V2_TEST
 **OS** - Linux

**Database** - BindingDB
Protein search using uniprot id **P03366**

1. At the time of protein search by giving above parameters, total 795 associated compounds were given, did a similarity search for all 795 compounds in which ChEMBL database was selected with 90 percent as similarity score. After that multiple alerts kept popping after that the system got crashed
2.  Alert message should be changed. The message needs to be more relevant and specific. 
**Example** 
Activity not found in ChEMBL database 
Activity not identified in the ChEMBL database 

**![Screenshot from 2023-02-20 11-01-05](https://user-images.githubusercontent.com/117424735/220021543-58c2ffe8-32ae-4650-9b0c-bc8f565ffe56.png)**

**Comment by bishweshwarShome** [comment]
fixed

commit id:  fd26cbf
