### ISSUE TITLE
Thread stopping abruptly, log and binding db smiles

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#49]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x (Internal release)
**OS** - Linux

1. Thread is stopping abruptly for similar drug search when ChEMBL database is selected. This happens if the select smiles are more in number(>100).
2. The SMILES column width should be fixed to avoid the alignment issues.
3. SMILES having space at the end are giving error in SyMogAI. 
4. While exporting pdbs and csv, the software directory is opening as default. This should be changed to project directory for user's convenience. 

![Screenshot from 2023-02-23 12-04-06](https://user-images.githubusercontent.com/117424735/221126322-b02c9630-4569-4044-bd36-4b30adbbcea2.png)
![Screenshot (184)](https://user-images.githubusercontent.com/117424735/221126409-e268313c-1cf8-4950-afef-167be5d48bb8.png)
![Screenshot from 2023-02-24 13-41-51](https://user-images.githubusercontent.com/117424735/221126676-a7597adf-956b-40af-848a-470bc0057466.png)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
