### ISSUE TITLE
'Similar drug search' with ChemBL not working 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#5]
windows version- TEST_V2_7
PIPL01

When chosen ChemBL for similarity search with UniProt ID Inputs from BindingDB, no results are produced. However, search with BindinDB database produces results.

![image](https://user-images.githubusercontent.com/111036161/189898773-3da8b393-eb62-4641-9238-ac5a71d5cd09.png)

**Comment by LobeliaG** [comment]
Same thing happened for UniProt ID inputs from ChemBL/UniProt_swissProt database.

**Comment by bishweshwarShome** [comment]
fixed

commit id: 17dd0f3
