### ISSUE TITLE
Graphical representation - scatter plot

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#50]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x
**OS** - Linux

1. In graphical representation section, when _figure options_ is selected from the menu bar displayed above the graph and below options are selected then the software gets crashed.

![Screenshot from 2023-04-03 14-26-43](https://user-images.githubusercontent.com/117424735/229466431-bc1ae2f9-10a9-4145-a8c2-3550dc1d8d8b.png)

2. The same drop down menu is coming in white color for graphical representation and similarity plot
![Screenshot from Screencast from 03-04-23 02:48:24 PM IST webm](https://user-images.githubusercontent.com/117424735/229467570-46f2aac3-381c-4451-ac06-d138e110384f.png)

**Comment by Akhilesh-pres** [comment]
The software is still crashes when changes made in figure options

**Comment by mdaakhan** [comment]
Already Solved in the previous version
