### ISSUE TITLE
Selection & generate synthetic molecules

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/ChemIn#51]
**Version** - Ubuntu 22 (Updated version for PyQt 6)
**OS** - Linux

1. Input parameters (Database - ChEMBL, Protein search using Unitprot id P03366)
The similar drug search and drug properties search is showing results for all the compounds irrespective if the selection

2. Unable to proceed for synthetic molecule generation

**Comment by mdaakhan** [comment]
Fixed 
V_Test_Pyqt6_1_3
