### ISSUE TITLE
Select all/Unselect all button not working on Drug properties page

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#6]
TEST_V2_7- windows
machine- PIPL01

The select buttons are not working. only manual selection is working.
![image](https://user-images.githubusercontent.com/111036161/189902155-165fdfbf-0779-4453-ae7e-279f522b3755.png)

**Comment by LobeliaG** [comment]
@bishweshwarShome it persists and also not working in similar drugs page as well in the PRinS_V_2_0_0 windows version.

**Comment by bishweshwarShome** [comment]
fixed.

commit id:   72182ff
