### ISSUE TITLE
'Generate synthetic molecules' does not transfer the SMILES

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#7]
TEST_V2_7- windows
PIPL01

On opting for 'Generate synthetic molecules' in ChemIn, the software is redirecting to SyMoG, but with no compound data.

![symogblank](https://user-images.githubusercontent.com/111036161/189909467-547b44d2-cd44-41d7-a126-33b135dd3c49.JPG)

**Comment by LobeliaG** [comment]
@bishweshwarShome  persists in the new PRinS_V_2_0_0 , windows version.

**Comment by bishweshwarShome** [comment]
fixed.

commit id:  eebecaf
