### ISSUE TITLE
Database-BindingDb- Property search not working

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/ChemIn#8]
TEST_V2_7
machine-PIPL01

Property search does not show results for inputs with BindingDB as selected database. Below is the snapshot of results for activity search, but on selecting show properties it just keeps loading.
![Capture](https://user-images.githubusercontent.com/111036161/189912954-18eedcea-0437-46b3-b598-e4f4e138b6fb.JPG)

**Comment by bishweshwarShome** [comment]
fixed.
commit id: 17dd0f3
