### ISSUE TITLE
BindingDB : Compounds Page

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/ChemIn#9]
Hi,

PRinS_Hackathon_Sep_Windows EXE
Windows machine

1. In 'Compounds' tab, First column is Titled as CHEMBLID and not BindingDB ID. 
2.  Upon double-click on smile, In 'Smile View' ID shown below smile is not matching with ID shown in row. 

![ChemIn_BindingDB_Compounds](https://user-images.githubusercontent.com/105902516/190324334-a68e58d9-81a7-48b9-8629-c38d0c5d1dd1.jpg)

**Comment by bishweshwarShome** [comment]
Header issue fixed.

and ID issue is from BindingDB side fixed now. (same ID in both table and image)
